services:

    sylius.google_tag_manager.listener.route:
        class: GtmPlugin\EventListener\AddRouteListener
        arguments:
            - "%gtm.features.route%"
            - "@google_tag_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
